#!/usr/bin/python
import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 


import web 
from config import settings

urls = ('/','twitterapi.ttcbk.index',
    '/auth','twitterapi.ttauth.auth',
    '/api/(.*)','twitterapi.ttapi.api',
)

app = web.application(urls, globals())
application = app.wsgifunc()
if __name__=="__main__":
#    app.run()
    pass

